name: Hostlist Compiler
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm i -g @adguard/hostlist-compiler
      - run: hostlist-compiler -c configuration.json -o om.ads

      - name: Commit files
        run: |
          git config --local user.email "dungsherlock@users.noreply.github.com"
          git config --local user.name "DungSherlock"
          git commit -m "Add changes" -a
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     personal_token: ${{ secrets.GH_TOKEN }}
      #     external_repository: DungSherlock/ads
      #     publish_dir: ./
      #     keep_files: false
      #     user_name: dungsherlock
      #     user_email: dungsherlock@gmail.com
      #     publish_branch: master
