name: Hostlist Compiler
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm i -g @adguard/hostlist-compiler
      - run: hostlist-compiler -c configuration.json -o om

      - name: Commit files
        run: |
          git config --local user.email "dungsherlock@users.noreply.github.com"
          git config --local user.name "DungSherlock"
          git add -A .
          git commit -am "Add changes"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
